package holidayiq.com.geofenced.geofence;

/**
 * Created by Manoj on 21/10/2016.
 */

public class HIQConstant {

    public static final String IN_APP_DATABASE_NAME = "hiq_in_app.sqlite";
    public static final int IN_APP_DATABASE_VERSION = 7;
    public static final String json_obj = "{\"iternary_list\":[{\"approved_photos\":[],\"destinations\":[],\"end_destination\":\"Mysore\",\"end_destination_id\":472,\"type\":\"journey\",\"start_destination_id\":293,\"start_destination\":\"Bangalore\",\"intermediate_destinations\":[{\"destination_id\":339,\"destination_name\":\"Coorg\",\"exited_time\":1477139713602,\"reached_time\":1477139240788}],\"photos\":[],\"rejected_photos\":[],\"exit_time\":0,\"enter_time\":0,\"start_time\":1477139065093,\"end_time\":1477140528715},{\"approved_photos\":[],\"destinations\":[],\"type\":\"destination\",\"intermediate_destinations\":[],\"object_id\":472,\"object_name\":\"Mysore\",\"parent_destination_id\":472,\"photos\":[],\"rejected_photos\":[],\"exit_time\":0,\"enter_time\":1477140528715,\"start_time\":0,\"end_time\":0},{\"approved_photos\":[],\"destinations\":[],\"type\":\"hotel\",\"intermediate_destinations\":[],\"object_id\":446777,\"object_name\":\"Zip Rooms Mysore Palace\",\"parent_destination_id\":472,\"parent_destination_name\":\"Mysore\",\"photos\":[],\"rejected_photos\":[],\"exit_time\":1477140528715,\"enter_time\":1477140449442,\"start_time\":0,\"end_time\":0},{\"approved_photos\":[],\"destinations\":[],\"type\":\"ss\",\"intermediate_destinations\":[],\"object_id\":665,\"object_name\":\"Mysore Zoo\",\"parent_destination_id\":472,\"parent_destination_name\":\"Mysore\",\"photos\":[],\"rejected_photos\":[],\"exit_time\":1477140413596,\"enter_time\":0,\"start_time\":0,\"end_time\":0},{\"approved_photos\":[],\"destinations\":[],\"type\":\"hotel\",\"intermediate_destinations\":[],\"object_id\":3523,\"object_name\":\"Regaalis Hotel\",\"parent_destination_id\":472,\"parent_destination_name\":\"Mysore\",\"photos\":[],\"rejected_photos\":[],\"exit_time\":1477140012560,\"enter_time\":1477139951424,\"start_time\":0,\"end_time\":0},{\"approved_photos\":[],\"destinations\":[],\"type\":\"hotel\",\"intermediate_destinations\":[],\"object_id\":2927,\"object_name\":\"Club Mahindra Madikeri\",\"parent_destination_id\":339,\"parent_destination_name\":\"Coorg\",\"photos\":[],\"rejected_photos\":[],\"exit_time\":1477139371176,\"enter_time\":1477139533841,\"start_time\":0,\"end_time\":0},{\"approved_photos\":[],\"destinations\":[],\"type\":\"ss\",\"intermediate_destinations\":[],\"object_id\":13769,\"object_name\":\"Abbi Falls\",\"parent_destination_id\":339,\"parent_destination_name\":\"Coorg\",\"photos\":[],\"rejected_photos\":[],\"exit_time\":1477139502928,\"enter_time\":1477139437993,\"start_time\":0,\"end_time\":0}]}";

}
